# Generated by Django 6.0.1 on 2026-02-04 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislike_users",
            field=models.ManyToManyField(
                blank=True, related_name="dislike_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="like_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
